### ISSUE TITLE
coma extra

### ISSUE THREAD

**Issue by eduardosalaz** [fanyCaz/filosofos#1]
#### Issue description
Hay una coma extra y me da ansiedad

#### Steps to reproduce the issue

1.  Ir a https://github.com/fanyCaz/filosofos
2. Entrar a docs/
3. Entrar a index.md

#### What's the expected result?

- Hola, mundo

#### What's the actual result?

- Hola , mundo

#### Additional details / screenshot

- ![https://prnt.sc/103c7mg]()

**Comment by eduardosalaz** [comment]
hola soy imbecil este es el link del screenshot https://prnt.sc/103c7mg

**Comment by fanyCaz** [comment]
This issue is boring, also, este commit lo arregla uwu 
https://github.com/fanyCaz/filosofos/commit/e66d97d9776880f5df4bef87672943ccdaa66461
